# Generated by Django 3.1.4 on 2021-01-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLecture', '0003_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
