# Generated by Django 3.1.4 on 2021-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLecture', '0004_auto_20210113_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(),
        ),
    ]
